#!/usr/bin/bash

chmod -R 777 lab0
rm -r lab0

#1

mkdir lab0
cd lab0
echo -e 'satk 10 sdef=8 spd=10' > arcanine4
mkdir cinccino6
echo -e 'satk-8 sdef=8\nspd=14' > cinccino6/electrode
mkdir cinccino6/sudowoodo
mkdir cinccino6/chingling
mkdir duskull6
echo -e 'weigth=67.2 height=43.0 atk-10\ndef=6' > duskull6/simisage
mkdir duskull6/roggenrola
mkdir duskull6/marshtomp
mkdir hariyama3
echo -e 'Способности Clamp Iron Defense Water Gun Whirlpool\nShell Smash' > hariyama3/clamperl
mkdir hariyama3/dusclops
echo -e 'Способности Dark Art Illusion\nPrankster' > hariyama3/zorua 
mkdir hariyama3/drowzee
echo -e 'satk 4 sdef=4 spd=5' > skitty8
echo -e 'Возможности\nOverland 8 Surface 6 Jump=4 Power 3 Intelligence 4 Tracker=0' > watchog0

#2
chmod u=rw, g=w, o=r arcanine4
chmod 363 cinccino6
chmod u=rw, g=w, o=w cinccino6/electrode
chmod 750 cinccino6/sudowoodo
chmod 311 cinccino6/chingling
chmod 755 duskull6
chmod u=r, g=r, o=r duskull6/simisage
chmod 512 duskull6/roggenrola
chmod 512 duskull6/marshtomp
chmod 330 hariyama3
chmod 540 hariyama3/clamperl
chmod u=rx, g=rwx, o=rw hariyama3/dusclops
chmod 640 hariyama3/zorua
chmod 573 hariyama3/drowzee
chmod 044 skitty8
chmod u=r, g=r, o=r watchog0

#3
chmod 777 skitty8
cp skitty8 cinccino6/sudowoodo

#Команда для проверки и результат
	#ls -p cinccino6/sudowoodo
	#skitty8

ln -s ../watchog0 hariyama3/clamperlwatchog

#Команда для проверки и результат
	#cat hariyama3/clamperlwatchog 
	#Возможности
	#Overland 8 Surface 6 Jump=4 Power 3 Intelligence 4 Tracker=0

ln skitty8 hariyama3/clamperlskitty

#Команда для проверки и результат
	#ls -li skitty8 hariyama3/clamperlskitty
	#12202120 -rwxrwxrwx  2 s466380 studs 0  7 нояб. 08:21 hariyama3/clamperlskitty
	#12202120 -rwxrwxrwx  2 s466380 studs 0  7 нояб. 08:21 skitty8

chmod 777 hariyama3
chmod 777 hariyama3/drowzee
cp -r hariyama3 hariyama3/drowzee

#Команда для проверки и результат
	#cd hariyama3/drowzee/hariyama3 
	#ls 
	#clamperl	clamperlskitty	drowzee		dusclops	zorua

ln -s ./cinccino6 Copy_28

#Команда для проверки и результат
	#ls -la | grep ^l
	#lrwxr-xr-x  1 s466380 studs 12 10 окт.  19:42 cinccino6 -> ../cinccino6

	#ls cinccino6
	#chingling	electrode	sudowoodo
	#ls Copy_28
	#chingling	electrode	sudowoodo

chmod 777 skitty8
cat skitty8 > hariyama3/clamperlskitty 

#Команда для проверки и результат
	#cat hariyama3/clamperlskitty
	#satk 4 sdef=4 spd=5

cat hariyama3/clamperl duskull6/simisage > arcanine4_99

#Команда для проверки и результат
	#cat hariyama3/clamperl
	#Способности Clamp Iron Defense Water Gun Whirlpool
	#Shell Smash

	#cat duskull6/simisage
	#weigth=67.2 height=43.0 atk-10
	#def=6

	#cat arcanine4_99
	#Способности Clamp Iron Defense Water Gun Whirlpool
	#Shell Smash
	#weigth=67.2 height=43.0 atk-10
	#def=6

#Дерево каталогов

ls -la
total 28
drwxr-xr-x  5 s466380 studs  8  9 окт.  16:19 .
drwxr-xr-x  4 s466380 studs 12  9 окт.  16:19 ..
-rw--w-r--  1 s466380 studs 22  9 окт.  16:19 arcanine4
drwxrwxrwx  4 s466380 studs  5  9 окт.  16:19 cinccino6
drwxr-xr-x  4 s466380 studs  5  9 окт.  16:19 duskull6
d-wx-wx---  4 s466380 studs  6  9 окт.  16:19 hariyama3
----r--r--  1 s466380 studs 20  9 окт.  16:19 skitty8
-r--r--r--  1 s466380 studs 84  9 окт.  16:19 watchog0

cd cinccino6
ls -la
total 11
drwxrwxrwx  4 s466380 studs  5  9 окт.  16:19 .
drwxr-xr-x  5 s466380 studs  8  9 окт.  16:19 ..
d-wx--x--x  2 s466380 studs  2  9 окт.  16:19 chingling
-rw--w--w-  1 s466380 studs 21  9 окт.  16:19 electrode
drwxr-x---  2 s466380 studs  2  9 окт.  16:19 sudowoodo

cd duskull6
ls -la
total 11
drwxr-xr-x  4 s466380 studs  5  9 окт.  16:19 .
drwxr-xr-x  5 s466380 studs  8  9 окт.  16:19 ..
dr-x--x-w-  2 s466380 studs  2  9 окт.  16:19 marshtomp
dr-x--x-w-  2 s466380 studs  2  9 окт.  16:19 roggenrola
-r--r--r--  1 s466380 studs 37  9 окт.  16:19 simisage

cd hariyama3
ls -la
total 19
drwxrwxrwx  4 s466380 studs  6  9 окт.  16:19 .
drwxr-xr-x  5 s466380 studs  8  9 окт.  16:19 ..
-r-xr-----  1 s466380 studs 74  9 окт.  16:19 clamperl
dr-xrwx-wx  2 s466380 studs  2  9 окт.  16:19 drowzee
dr-xrwxrw-  2 s466380 studs  2  9 окт.  16:19 dusclops
-rw-r-----  1 s466380 studs 51  9 окт.  16:19 zorua

#4


wc -l cinccino6/electrode duskull6/simisage hariyama3/clamperl 2>/dev/null | sort | grep -v total

#Результат
	#2 cinccino6/electrode
	#2 duskull6/simisage
	#2 hariyama3/clamperl

ls -lRa duskull6 2>/dev/null | sort -k 7 | grep ^-

#Результат работы
	#-r--r--r--  1 s466380 studs 37  9 окт.  16:19 simisage

cat -n arcanine4 2>&1 | sort -f | grep -v 'de' 

#Результат работы
	     #1	test test test

cat -n cinccino6/electrode | grep 'n$'

#Результат работы
	     #2	nonamen

ls -lacR 2>&1 | grep -e ':[0-5][0-9] [.a-z0-9]*6$' | head -n3

#Результат работы
	#-rw-r--r--  1 s466380 studs    0 24 окт.  11:13 .lll6
	#drwxr-xr-x  4 s466380 studs    5 24 окт.  10:41 cinccino6
	#drwxr-xr-x  4 s466380 studs    5 24 окт.  10:41 duskull6

cat -n arcanine4 2>/tmp/hsperfdata_s466380 | grep 'n$'

#Результат работы
	     #2	nonon

#5

rm arcanine4
chmod u+w duskull6/simisage
rm duskull6/simisage
rm hariyama3/clamperlwatchog*
rm hariyama3/clamperlskit*
chmod -R 777 cinccino6
rm -drf cinccino6
rm -rf cinccino6/sudowoodo
